name: mystic 
markdown: redcarpet
highlighter: pygments
excerpt_separator: <!--more-->
paginate: 3
paginate_path: "blog/page:num"
permalink: /blog/:title
disqus:
  config:
    - label: disqus_shortname
      value: 'gotmystic'
googleanalytics:
  account: UA-254925-1